language: java
sudo: false # faster builds

notifications:
  email: false
cache:
  directories:
  - "$HOME/.gradle/caches/"
jdk:
  - oraclejdk7

before_install:
 - chmod +x gradlew
deploy:
  provider: releases
  api_key:
    secure: fMu9Vl1dYaMH1elMvXdZ5b/QvSedu7ckT8C5LXettqACg0JcJz9ScO7U8CdWf0gJF8eesiFsIvIaxdlSOMwhv6XLJ51pqM6G8NWGWs5+eEtZ3aqQc9fQaMcoCiwppeV7SAnSQlPc6/v6YzqDQwApX4ICkjrffZhFErkK/V48tByY5OFIEY3dKT0dUjuH7jIh0IrtXGvUvBUKZr+wLhIVxuTmT3YQn6zMnHIhI6VuX2iL0ivFB2uEx5gUBVb2E2ugJNZ8o8s4LfeWcI+Nq01F3t3tIwuR3q5P0GAyXM5JfDkgcbzxc+49zERBmYg76fSiP2PS1CHlZpQcJRv0+E5fPhuGVKdO+E2wxtbnGILIAzKVCqirgyz9rtmfsTNUKb2LmLr44JFwN3jspb7kAlKWZxVhAtjfCDtKZ7X2QO8dU3xivxk30bqURMJT4LofJq+EresqAHUer7wX0IclO/aPO4xKIJ0fa+O8//1NClTQWz0dT1+xEv/xBKCAx2nmBTdBVgs/Q60KiToBenKWh8v9oJ2nwpBaW3HJ9nJyNKuURcYOF53gkN441mHAfUwcYFTdMQhJdnftR9QbofOmeoMEwQi5FgLt6+CKw8x8q5E6JbZKIpBqXSq+/aPE/7HaCX5L2bQu+erZ4HsodkIsF2ilIYVOLqkdNWF34iDA8Kg2svw=
  file: "build/libs/*.jar"
  skip_cleanup: true
  on:
    tags: true
    repo: Namikon/WarpTheory
