language: java
sudo: false # faster builds

notifications:
  email: false
cache:
  directories:
  - "$HOME/.gradle/caches/"
jdk:
  - oraclejdk7
  - openjdk7
 
before_install:
 - chmod +x gradlew

after_success:
- bash <(curl -s https://codecov.io/bash) -v
